[package]
name = "web_server"
version = "0.1.0"
authors = ["Stefan Zabka <zabkaste@informatik.hu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
handlebars = "3.2.1"
serde = {version="1.0.114", features = ["derive"]}
serde_json = "1.0.56"